# i18n-tasks finds and manages missing and unused translations: https://github.com/glebm/i18n-tasks

# The "main" locale.
base_locale: en

## Reporting locale, default: en. Available: en, ru.
# internal_locale: en

# Read and write translations.
data:
  ## Translations are read from the file system. Supported format: YAML, JSON.
  ## Provide a custom adapter:
  # adapter: I18n::Tasks::Data::FileSystem

  # Locale files or `File.find` patterns where translations are read from:
  read:
    - config/locales/%{locale}.yml

  # Locale files to write new keys to, based on a list of key pattern => file rules. Matched from top to bottom:
  # `i18n-tasks normalize -p` will force move the keys according to these rules
  write:
    - config/locales/%{locale}.yml

  ## Specify the router (see Readme for details). Valid values: conservative_router, pattern_router, or a custom class.
  # router: convervative_router

  yaml:
    write:
      # do not wrap lines at 80 characters
      line_width: -1

  ## Pretty-print JSON:
  # json:
  #   write:
  #     indent: '  '
  #     space: ' '
  #     object_nl: "\n"
  #     array_nl: "\n"

# Find translate calls
search:
  ## Paths or `File.find` patterns to search in:
  paths:
    - app
    - lib

  # Root directories for relative keys resolution.
  relative_roots:
    - app/controllers
    - app/helpers
    - app/mailers
    - app/presenters
    - app/services
    - app/views
    - app/cells

  ## Files or `File.fnmatch` patterns to exclude from search. Some files are always excluded regardless of this setting:
  ##   %w(*.jpg *.png *.gif *.svg *.ico *.eot *.otf *.ttf *.woff *.woff2 *.pdf *.css *.sass *.scss *.less *.yml *.json)
  exclude:
    - "*.jpeg"
    - "*.odt"
    - "*.docx"
    - "app/compiled_views/**/*"

  ## Alternatively, the only files or `File.fnmatch patterns` to search in `paths`:
  ## If specified, this settings takes priority over `exclude`, but `exclude` still applies.
  # only: ["*.rb", "*.html.slim"]

  ## If `strict` is `false`, guess usages such as t("categories.#{category}.title"). The default is `true`.
  strict: false

  ## Multiple scanners can be used. Their results are merged.
  ## The options specified above are passed down to each scanner. Per-scanner options can be specified as well.
  ## See this example of a custom scanner: https://github.com/glebm/i18n-tasks/wiki/A-custom-scanner-example

## Google Translate
# translation:
#   # Get an API key and set billing info at https://code.google.com/apis/console to use Google Translate
#   api_key: "AbC-dEf5"

translation:
  deepl_api_key: <%= ENV["DEEPL_API_KEY"] %>

# Do not consider these keys missing:
ignore_missing:
 - faker.*
 - activemodel.attributes.common.created_at
 - decidim.endorsable.endorsements_count
 - decidim.endorsable.endorsements
 - decidim.proposals.proposals.votes_count.most_popular_proposal
 - decidim.proposals.proposals.votes_count.need_more_votes
 - decidim.proposals.proposals.edit.select_a_category
 - decidim.proposals.proposals.edit.delete_image
 - decidim.proposals.proposals.edit.add_images
 - decidim.proposals.proposals.edit.attachment_legend
 - decidim.proposals.proposals.edit.delete_document
 - decidim.proposals.proposals.edit.add_documents
 - decidim.proposals.proposals.placeholder.address
 - decidim.proposals.collaborative_drafts.edit.select_a_category
 - decidim.proposals.collaborative_drafts.edit.attachment_legend
 - decidim.account.email_change.*
 - decidim.account.show.*
 - layouts.decidim.user_menu.profile
 - activemodel.attributes.proposal.address
 - devise.shared.links.sign_in_with_provider
 - decidim.devise.shared.omniauth_buttons.or
 - decidim.proposals.admin.proposals.bulk-actions.statuses
 - layouts.decidim.process_header_steps.{step,view_steps}
 - decidim.shared.extended_navigation_bar.{more,unfold}
 - decidim.budgets.admin.projects.index.*
 - decidim.budgets.admin.models.project.name
 - decidim.budgets.actions.*
 - decidim.budgets.models.project.fields.*
 - decidim.admin.actions.import
 - decidim.budgets_importer.actions.import
 - index.confirmed_orders_count
 - decidim.proposals.proposals.index.{new_proposal,collaborative_drafts_list}
 - decidim.decidim_awesome.admin.proposal_custom_fields.*
# Consider these keys used:
ignore_unused:
  - faker.*
  - activemodel.attributes.osp_authorization_handler.*
  - activemodel.attributes.participatory_process.private_space
  - decidim.accessibility.skip_button
  - decidim.authorization_handlers.osp_authorization_handler.*
  - decidim.authorization_handlers.osp_authorization_workflow.*
  - decidim.amendments.emendation.announcement.evaluating
  - decidim.events.budgets.pending_order.*
  - decidim.verifications.authorizations.first_login.actions.osp_authorization_handler
  - decidim.verifications.authorizations.first_login.actions.osp_authorization_workflow
  - layouts.decidim.user_menu.account
  - activemodel.attributes.proposal.address
  - activemodel.errors.models.proposal.attributes.attachment.needs_to_be_reattached
  - budgets.projects_helper.current_rule_description.*
  - budgets.projects_helper.current_rule_explanation.*
  - decidim.admin.exports.export_as
  - decidim.components.budgets.settings.global.geocoding_enabled
  - decidim.budgets.actions.*
  - decidim.budgets.admin.budgets.index.*
  - decidim.budgets.admin.models.budget.name
  - decidim.budgets.admin.reminders.orders.*
  - decidim.budgets.models.budget.fields.*
  - decidim.budgets.vote_reminder_mailer.vote_reminder.*
  - decidim.devise.sessions.new.sign_in_disabled
  - decidim.events.notifications_settings.show.*
  - decidim.events.users.user_officialized.*
  - decidim.events.verifications.verify_with_managed_user.*
  - decidim.events.verifications.verify_with_managed_user.notification_title
  - decidim.meetings.directory.meetings.index.all
  - decidim.meetings.meeting.not_allowed
  - decidim.meetings.meetings.create.*
  - decidim.meetings.meetings.update.*
  - decidim.omniauth.france_connect.*
  - decidim.proposals.admin.exports.awesome_private_proposals
  - decidim.proposals.admin.exports.proposal_comments
  - decidim.proposals.collaborative_drafts.collaborative_draft.publish.*
  - decidim.proposals.collaborative_drafts.collaborative_draft.withdraw.*
  - decidim.proposals.collaborative_drafts.create.*
  - decidim.proposals.collaborative_drafts.new.*
  - decidim.proposals.collaborative_drafts.show.*
  - decidim.proposals.collaborative_drafts.update.*
  - decidim.proposals.collaborative_drafts.wizard_aside.*
  - decidim.proposals.index.collaborative_drafts_list
  - decidim.proposals.index.new_proposal
  - decidim.proposals.index.view_proposal
  - decidim.proposals.models.collaborative_draft.fields.*
  - decidim.scopes.global
  - decidim.scopes.picker.*
  - decidim.shared.login_modal.*
  - decidim.system.organizations.omniauth_settings.france_connect.*
  - decidim.system.organizations.omniauth_settings.france_connect_profile.*
  - decidim.system.organizations.omniauth_settings.france_connect_uid.*
  - decidim.system.organizations.omniauth_settings.publik.*
  - decidim.verifications.authorizations.create.error
  - decidim.verifications.authorizations.create.success
  - devise.passwords.new.forgot_your_password
  - devise.passwords.new.send_me_reset_password_instructions
  - devise.sessions.new.sign_in
  - devise.shared.links.forgot_your_password
  - devise.shared.links.sign_in_with_france_connect
  - layouts.decidim.footer.made_with_open_source
  - decidim.proposals.admin.proposals.bulk-actions.statuses
  - decidim.participatory_processes.show.local_area
