:concurrency: 5
:max_retries: 5
:queues:
  - default
  - backups
  - metrics
  - mailers
  - newsletter
  - events
  - scheduled
  - exports
  - user_report
  - block_user
  - active_storage_analysis
  - active_storage_purge
  - translations

:scheduler:
  :schedule:
    CalculateAllMetrics:
      cron: '0 0 0 * * *' # Run at midnight
      class: CalculateAllMetricsJob
      queue: scheduled
    PreloadOpenData:
      cron: '0 0 1 * * *' # Run at 01:00
      class: PreloadOpenDataJob
      queue: scheduled
    Backup:
      cron: '0 0 4 * * *' # Run at 04:00
      class: BackupJob
      queue: backups
    DetectSpamUsers:
      cron: '0 <%= Random.rand(0..59) %> <%= Random.rand(6..8) %> * * *' # Run randomly between 06:00 and 08:59
      class: Decidim::SpamDetection::MarkUsersJob
      queue: scheduled
    SendNotificationMailDaily:
      cron: '0 0 7 * * *' # Run at 07:00AM every days
      class: NotificationsDigestMailJob
      queue: mailers
      args: :daily
    SendNotificationMailWeekly:
      cron: '0 0 8 * * 2' # Run at 08:00AM on Tuesday
      class: NotificationsDigestMailJob
      queue: mailers
      args: :weekly
    SpamBotBlockUsers:
      cron: '0 <%= Random.rand(0..59) %> <%= Random.rand(6..8) %> * * *' # Run randomly between 06:00 and 08:59
      class: Decidim::SpamDetection::BlockUsersJob
      queue: default
      enabled: false
