:concurrency: 5
:queues:
  - default
  - backups
  - metrics
  - mailers
  - newsletter
  - events
  - scheduled
  - exports
  - active_storage_analysis
  - active_storage_purge
  - user_report
  - translations

:scheduler:
  :schedule:
    CalculateAllMetrics:
      cron: '0 0 0 * * *' # Run at midnight
      class: CalculateAllMetricsJob
      queue: scheduled
    PreloadOpenData:
      cron: '0 0 1 * * *' # Run at 01:00
      class: PreloadOpenDataJob
      queue: scheduled
    Backup:
      cron: '0 0 4 * * *' # Run at 04:00
      class: BackupJob
      queue: backups
    SendNotificationMailDaily:
      cron: '0 0 7 * * *' # Run at 07:00AM every days
      class: NotificationsDigestMailJob
      queue: mailers
      args: :daily
    SendNotificationMailWeekly:
      cron: '0 0 8 * * 2' # Run at 08:00AM on Tuesday
      class: NotificationsDigestMailJob
      queue: mailers
      args: :weekly